#%RAML 1.0 DataType

properties:
  name:
    description: Name of the Customer
    required: true
    type: string
  emailId:
    description: Email of the Customer
    required: true
    type: string
  systemName:
    description: System Name
    required: true
    type: string
  systemShortName:
    description: System Short Name
    required: true
    type: string
  systemDesc:
    description: Description about the System
    required: true
    type: string
