#%RAML 1.0 DataType

properties:
  mobileNum:
    description: Mobile No. of the Customer
    required: false
    type: string
  emailId:
    description: Email of the Customer
    required: false
    type: string
  code:
    description: Received OTP
    required: true
    type: string
