#%RAML 1.0 DataType

properties:
  planType:
    description: This is the Plan type of the Subscription
    required: true
    type: string
  renewalType:
    description: This is the Renewal type of the Subscription
    required: true
    type: string
  amount:
    description: This is the Amount or Charge for the Subscription
    required: true
    type: number
  currency:
    description: This is the Currency
    required: true
    type: string
