#%RAML 1.0 DataType

properties:
  subscriptionCustomerId:
    description: This is the ID of the Subscription Customer
    required: false
    type: integer
  customerId:
    description: This is the Customer Reference ID from Stripe Payment Gateway
    required: false
    type: string
  customerName:
    description: This is the name of the Customer
    required: true
    type: string
