/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.17).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.proarchs.notification.controller;

import java.util.List;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.proarchs.notification.model.Otpverificationcheck;
import com.proarchs.notification.model.Otpverificationcheckresponse;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-12-26T15:48:10.047Z")

@Api(value = "otpverificationcheck", description = "the otpverificationcheck API")
@RequestMapping(value = "/pnms")
public interface OtpverificationcheckApi {

    @ApiOperation(value = "Otpverificationcheck_GET", nickname = "otpverificationcheckGET", notes = "Get a list of Otpverificationcheck", response = Otpverificationcheck.class, responseContainer = "List", tags={ "otpverificationcheck", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Otpverificationcheck.class, responseContainer = "List") })
    @RequestMapping(value = "/otpverificationcheck",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<Otpverificationcheck>> otpverificationcheckGET();


    @ApiOperation(value = "Otpverificationcheck_POST", nickname = "otpverificationcheckPOST", notes = "Add a new Otpverificationcheck", response = Otpverificationcheckresponse.class, tags={ "otpverificationcheck", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "", response = Otpverificationcheckresponse.class) })
    @RequestMapping(value = "/otpverificationcheck",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<String> otpverificationcheckPOST(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Otpverificationcheck body) throws IllegalAccessException, InstantiationException;

}
