/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.17).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.proarchs.notification.controller;

import java.util.List;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.proarchs.notification.model.Otpverification;
import com.proarchs.notification.model.Otpverificationresponse;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-12-24T18:38:38.170Z")

@Api(value = "otpverification", description = "the otpverification API")
@RequestMapping(value = "/pnms")
public interface OtpverificationApi {

    @ApiOperation(value = "Otpverification_GET", nickname = "otpverificationGET", notes = "Get a list of Otpverification", response = Otpverification.class, responseContainer = "List", tags={ "otpverification", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Otpverification.class, responseContainer = "List") })
    @RequestMapping(value = "/otpverification",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<Otpverification>> otpverificationGET();


    @ApiOperation(value = "Otpverification_POST", nickname = "otpverificationPOST", notes = "Add a new Otpverification", response = Otpverificationresponse.class, tags={ "otpverification", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "", response = Otpverificationresponse.class) })
    @RequestMapping(value = "/otpverification",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<String> otpverificationPOST(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Otpverification body) throws IllegalAccessException, InstantiationException;

}
