/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.17).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.toystore.ecomm.payments.controller;

import java.text.ParseException;
import java.util.List;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.stripe.exception.StripeException;
import com.toystore.ecomm.payments.model.Subscriptionproduct;
import com.toystore.ecomm.payments.model.Subscriptionproductresponse;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-11-06T13:12:16.732Z")

@Api(value = "subscriptionproduct", description = "the subscriptionproduct API")
@RequestMapping(value = "/payments")
public interface SubscriptionproductApi {

    @ApiOperation(value = "Subscriptionproduct_GET", nickname = "subscriptionproductGET", notes = "Get a list of Subscriptionproduct", response = Subscriptionproduct.class, responseContainer = "List", tags={ "subscriptionproduct", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Subscriptionproduct.class, responseContainer = "List") })
    @RequestMapping(value = "/subscriptionproduct",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<Subscriptionproduct>> subscriptionproductGET();


    @ApiOperation(value = "Subscriptionproduct_POST", nickname = "subscriptionproductPOST", notes = "Add a new Subscriptionproduct", response = Subscriptionproductresponse.class, tags={ "subscriptionproduct", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "", response = Subscriptionproductresponse.class) })
    @RequestMapping(value = "/subscriptionproduct",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<String> subscriptionproductPOST(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Subscriptionproduct body) throws IllegalAccessException, InstantiationException, StripeException, ParseException, JsonProcessingException;

}
