/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.17).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.toystore.ecomm.payments.controller;

import java.util.List;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.stripe.exception.StripeException;
import com.toystore.ecomm.payments.model.Subscriptioncustomer;
import com.toystore.ecomm.payments.model.Subscriptioncustomerresponse;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-11-06T13:12:16.732Z")

@Api(value = "subscriptioncustomer", description = "the subscriptioncustomer API")
@RequestMapping(value = "/payments")
public interface SubscriptioncustomerApi {

    @ApiOperation(value = "Subscriptioncustomer_GET", nickname = "subscriptioncustomerGET", notes = "Get a list of Subscriptioncustomer", response = Subscriptioncustomer.class, responseContainer = "List", tags={ "subscriptioncustomer", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Subscriptioncustomer.class, responseContainer = "List") })
    @RequestMapping(value = "/subscriptioncustomer",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<Subscriptioncustomer>> subscriptioncustomerGET();


    @ApiOperation(value = "Subscriptioncustomer_POST", nickname = "subscriptioncustomerPOST", notes = "Add a new Subscriptioncustomer", response = Subscriptioncustomerresponse.class, tags={ "subscriptioncustomer", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "", response = Subscriptioncustomerresponse.class) })
    @RequestMapping(value = "/subscriptioncustomer",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<String> subscriptioncustomerPOST(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Subscriptioncustomer body) throws IllegalAccessException, InstantiationException, StripeException, JsonProcessingException;

}
